CREATE DATABASE APP_NOTAS DEFAULT CHARACTER SET = 'utf8mb4';

CREATE TABLE
    notasText(
        id INT NOT NULL PRIMARY KEY,
        titulo VARCHAR(100) NOT NULL,
        texto VARCHAR(255) NOT NULL
    ) DEFAULT CHARSET UTF8 COMMENT 'newTable';